### ISSUE TITLE
No Such Method Error => setAllowEncryptedValueModifications

### ISSUE THREAD

**Issue by joejy0109** [Azure/azure-sqldb-spark#12]
I am trying to bulk copy from Spark to the database.
But I gets an error at Azure HDInsight.
Please, Help!

Using: 
  azure-sqldb-spark-1.0.0.jar
  or azure-sqldb-spark-1.0.0-uber.jar
  or azure-sqldb-spark-1.0.1-jar-with-dependencies.jar

Env:
   Azure HDInsight: Spark 2.1 on Linux (HDI 3.6)
   SQL Server: SQL Server 2016 on VM

Error:
   Error: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 1.0 failed 4 times, most recent failure: Lost task 0.3 in stage 1.0 (TID 4, wn4-y17hsm.npb0fipud0iuhixtnxb1j2miud.ax.internal.cloudapp.net, executor 1): java.lang.NoSuchMethodError: com.microsoft.sqlserver.jdbc.SQLServerBulkCopyOptions.setAllowEncryptedValueModifications(Z)V
	at com.microsoft.azure.sqldb.spark.bulk.BulkCopyUtils$.getBulkCopyOptions(BulkCopyUtils.scala:109)
	at com.microsoft.azure.sqldb.spark.connect.DataFrameFunctions.com$microsoft$azure$sqldb$spark$connect$DataFrameFunctions$$bulkCopy(DataFrameFunctions.scala:121)
	at com.microsoft.azure.sqldb.spark.connect.DataFrameFunctions$$anonfun$bulkCopyToSqlDB$1.apply(DataFrameFunctions.scala:67)
	at com.microsoft.azure.sqldb.spark.connect.DataFrameFunctions$$anonfun$bulkCopyToSqlDB$1.apply(DataFrameFunctions.scala:67)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$29.apply(RDD.scala:926)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$29.apply(RDD.scala:926)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1954)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1954)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:99)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:322)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by joejy0109** [comment]
(My English is not good. sorry)
I also included it in jars, but I got the same error.
I think we should get it to run with the jdbc driver in jars, not the jdbc driver installed on Azure HDinsight.
Is there a way?

**Comment by jryu01** [comment]
I'm still getting exactly same error with followings:

azure-sqldb-spark:1.0.2
Azure sql database
Spark 2.3 (HDI 3.6)

Has anyone found solution for this issue?
Or is this issue even being worked on?

**Comment by mmchougule** [comment]
Also getting this error. I have downloaded this jar: https://search.maven.org/remotecontent?filepath=com/microsoft/azure/azure-sqldb-spark/1.0.2/azure-sqldb-spark-1.0.2-jar-with-dependencies.jar. Including this jar in spark-shell.

```
    import com.microsoft.azure.sqldb.spark.config.Config
    import com.microsoft.azure.sqldb.spark.connect._

      val config = Config(Map(
        "url"          -> "temp.database.windows.net",
        "databaseName" -> "dbtemp",
        "dbTable"      -> "schema.Clients",
        "user"         -> "abcusername",
        "password"     -> "*****"
      ))

      val collection = getSpark().read.sqlDB(config)
      collection.show()

```

Here is my code, same as the examples and I am getting no suitable driver.
`java.sql.SQLException: No suitable driver`

Anyone know how to fix this?

**Comment by arvindshmicrosoft** [comment]
HDI ships with a 4.x version of the SQL Server JDBC driver, which does not have the said property. Please add the later SQL JDBC driver 7.0 to your HDI cluster and specify that JAR in your --jars https://docs.microsoft.com/en-us/sql/connect/jdbc/download-microsoft-jdbc-driver-for-sql-server?view=sql-server-2017

**Comment by arvindshmicrosoft** [comment]
Closing due to inactivity.
