### ISSUE TITLE
Does it support using the Windows domain account?

### ISSUE THREAD

**Issue by java8964** [Azure/azure-sqldb-spark#14]
Our application is running on Linux OS, but remote SQL server is using Windows Domain account to access. (We have the domain username/password in the application)

We have to use net.sourceforge.jtds JDBC driver in Spark, which works fine, but performance is not as good as we want.

I gave azure-sqldb-spark a try, and below is the error I got in the Spark shell:

scala> spark.version
res1: String = 2.2.0
scala> val account = spark.read.sqlDB(config)
18/08/03 09:11:20 **_ERROR JniBasedUnixGroupsMapping: error looking up the name of group 239613470: No such file or directory
java.sql.SQLException: No suitable driver_**
  at java.sql.DriverManager.getDriver(DriverManager.java:315)
  at org.apache.spark.sql.execution.datasources.jdbc.JDBCOptions$$anonfun$7.apply(JDBCOptions.scala:84)
  at org.apache.spark.sql.execution.datasources.jdbc.JDBCOptions$$anonfun$7.apply(JDBCOptions.scala:84)
  at scala.Option.getOrElse(Option.scala:121)
  at org.apache.spark.sql.execution.datasources.jdbc.JDBCOptions.<init>(JDBCOptions.scala:83)
  at org.apache.spark.sql.execution.datasources.jdbc.JDBCOptions.<init>(JDBCOptions.scala:34)
  at org.apache.spark.sql.execution.datasources.jdbc.JdbcRelationProvider.createRelation(JdbcRelationProvider.scala:34)
  at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:309)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:178)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:146)
  at org.apache.spark.sql.DataFrameReader.jdbc(DataFrameReader.scala:193)
  at com.microsoft.azure.sqldb.spark.connect.DataFrameReaderFunctions.sqlDB(DataFrameReaderFunctions.scala:44)
  ... 50 elided

**Comment by arvindshmicrosoft** [comment]
Out of scope for this connector. The [newer connector](https://github.com/microsoft/sql-spark-connector) has Windows Auth support. Please evaluate and consider using that one.
