### ISSUE TITLE
Breaking Connection with 20 TB's of data

### ISSUE THREAD

**Issue by chetkhatri** [Azure/azure-sqldb-spark#18]
18/09/03 14:20:55 INFO Client: 
	 client token: N/A
	 diagnostics: User class threw exception: com.microsoft.sqlserver.jdbc.SQLServerException: The TCP/IP connection to the host ZUSSCNTP2DBM01.dev.cluster.com, port 1433 has failed. Error: "Connection timed out: no further information.. Verify the connection properties. Make sure that an instance of SQL Server is running on the host and accepting TCP/IP connections at the port. Make sure that TCP connections to the port are not blocked by a firewall.".
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDriverError(SQLServerException.java:228)
	at com.microsoft.sqlserver.jdbc.SQLServerException.ConvertConnectExceptionToSQLServerException(SQLServerException.java:285)
	at com.microsoft.sqlserver.jdbc.SocketFinder.findSocket(IOBuffer.java:2437)
	at com.microsoft.sqlserver.jdbc.TDSChannel.open(IOBuffer.java:641)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:2245)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:1921)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:1762)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1077)
	at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:623)
	at org.apache.spark.sql.execution.datasources.jdbc.DriverWrapper.connect(DriverWrapper.scala:45)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$$anonfun$createConnectionFactory$1.apply(JdbcUtils.scala:63)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$$anonfun$createConnectionFactory$1.apply(JdbcUtils.scala:54)
	at org.apache.spark.sql.execution.datasources.jdbc.JDBCRDD$.resolveTable(JDBCRDD.scala:56)
	at org.apache.spark.sql.execution.datasources.jdbc.JDBCRelation.<init>(JDBCRelation.scala:115)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcRelationProvider.createRelation(JdbcRelationProvider.scala:52)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:340)
	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:239)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:227)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:164)
	at org.apache.spark.sql.DataFrameReader.jdbc(DataFrameReader.scala:254)
	at com.microsoft.azure.sqldb.spark.connect.DataFrameReaderFunctions.sqlDB(DataFrameReaderFunctions.scala:44)
	at com.sample.spark.invoice.ClientInvoiceHeader$.main(ClientInvoiceHeader.scala:111)
	at com.sample.spark.invoice.ClientInvoiceHeader.main(ClientInvoiceHeader.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$4.run(ApplicationMaster.scala:721)

	 ApplicationMaster host: 10.44.81.98
	 ApplicationMaster RPC port: 0
	 queue: default
	 start time: 1535972791147
	 final status: FAILED
	 tracking URL: http://research.dev.cluster.com:8088/proxy/application_1535626002733_0086/
	 user: spark
Exception in thread "main" org.apache.spark.SparkException: Application application_1535626002733_0086 finished with failed status
	at org.apache.spark.deploy.yarn.Client.run(Client.scala:1230)
	at org.apache.spark.deploy.yarn.YarnClusterApplication.start(Client.scala:1585)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:906)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:197)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:227)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:136)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

**Comment by arvindshmicrosoft** [comment]
Do you see any errors logged at the SQL Server side which correspond to this error? And when you say 20TBs of data, can you clarify exactly what that size refers to? Is that the size of the target database? What is the size of this dataframe? Without more details and hopefully repro code it is difficult to tell what's going on.

**Comment by arvindshmicrosoft** [comment]
As it is very context-specific, and would be better addressed through a support incident or such. Also as there was no activity subsequently on the Issue, closing.
