### ISSUE TITLE
Unable to connect to SQL Server instance of an Azure VM - TCP/IP connection on port 1433 failed

### ISSUE THREAD

**Issue by der-datenzauberer** [Azure/azure-sqldb-spark#42]
I am getting the below error message, every time I try to connect to a SQL Server instance hosted on an Azure VM from **Azure Databricks**. The VM name goes something like **azeunxyz001.juuw.net.** (modified)

Please refer to the image below:-
![issue](https://user-images.githubusercontent.com/11174526/61318510-e5d7f280-a822-11e9-814e-c876e81bbf7f.PNG)

I already tried the following resolutions that I found on the internet, but none of them worked.
1. Asking the DBAs to open port 1433 from SQL Server Configuration Manager
2. Asked the Infrastructure team and got confirmation that the firewall was turned off for this VM and that the port 1433 is not blocked.

What else am I missing?

Error message:-
`com.microsoft.sqlserver.jdbc.SQLServerException: The TCP/IP connection to the host azeuncpmd001.guww.net, port 1433 has failed. Error: "azeunxyz001.juuw.net. Verify the connection properties. Make sure that an instance of SQL Server is running on the host and accepting TCP/IP connections at the port. Make sure that TCP connections to the port are not blocked by a firewall."`

**Comment by DochertySt-OPS** [comment]
pop the following into a notebook section and see what the result is. it could be that you aren't able to resolve the name properly.
```
%sh

nslookup azeuncpmd001.guww.net
```

**Comment by sudarjs** [comment]
Unable to connect on-premise SQL server.

Error:
Exception in thread "main" java.lang.NoClassDefFoundError: scala/Product$class
	at com.microsoft.azure.sqldb.spark.config.SqlDBConfigBuilder.<init>(SqlDBConfigBuilder.scala:31)
	at com.microsoft.azure.sqldb.spark.config.Config$.apply(Config.scala:254)
	at com.microsoft.azure.sqldb.spark.config.Config$.apply(Config.scala:235)

**Comment by arvindshmicrosoft** [comment]
The original issue in this thread is typically due to networking configuration. Specifically for Azure VMs, the [network security group](https://docs.microsoft.com/en-us/azure/azure-sql/virtual-machines/windows/security-considerations-best-practices) at the Azure VNET and / or the Azure VM level is what you should check. In addition, another consideration is to associate your Azure Databricks workspace with [VNET injection](https://docs.microsoft.com/en-us/azure/databricks/administration-guide/cloud-configurations/azure/vnet-inject) and thereby have the Azure Databricks cluster VMs run directly within the same VNET as your Azure SQL VM.

Closing this issue as it is unlikely that the problem is due to the connector specifically.
