### ISSUE TITLE
dataframe.bulkCopyToSqlDB exception when using databricks-connect

### ISSUE THREAD

**Issue by eparizzi** [Azure/azure-sqldb-spark#44]
I have a Spark application written in Scala and I'm using databricks-connect to run the application on my databricks cluster. Everything works flawlessly except this library.

When I try to ´df.bulkCopyToSqlDB(config)`, after some time I get the following exception:

```
Exception in thread "main" java.lang.AssertionError: assertion failed
	at scala.Predef$.assert(Predef.scala:156)
	at com.databricks.service.SparkServiceClassSync$.checkSynced(SparkServiceClassSync.scala:226)
	at org.apache.spark.sql.util.ProtoSerializer.org$apache$spark$sql$util$ProtoSerializer$$writeReplaceClassDescriptor(ProtoSerializer.scala:2808)
	at org.apache.spark.sql.util.ProtoSerializer$$anon$1.writeClassDescriptor(ProtoSerializer.scala:2799)
	at java.io.ObjectOutputStream.writeNonProxyDesc(ObjectOutputStream.java:1282)
	at java.io.ObjectOutputStream.writeClassDesc(ObjectOutputStream.java:1231)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1427)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at org.apache.spark.sql.util.ProtoSerializer.serializeShadeAnonFun(ProtoSerializer.scala:2802)
	at org.apache.spark.sql.util.ProtoSerializer.serializeObject(ProtoSerializer.scala:2778)
	at com.databricks.service.SparkServiceRPCClientStub$$anonfun$executeRDD$1.apply(SparkServiceRPCClientStub.scala:256)
	at com.databricks.service.SparkServiceRPCClientStub$$anonfun$executeRDD$1.apply(SparkServiceRPCClientStub.scala:248)
	at com.databricks.spark.util.Log4jUsageLogger.recordOperation(UsageLogger.scala:172)
	at com.databricks.spark.util.UsageLogging$class.recordOperation(UsageLogger.scala:297)
	at com.databricks.service.SparkServiceRPCClientStub.recordOperation(SparkServiceRPCClientStub.scala:60)
	at com.databricks.service.SparkServiceRPCClientStub.executeRDD(SparkServiceRPCClientStub.scala:248)
	at com.databricks.service.SparkClient$.executeRDD(SparkClient.scala:204)
	at com.databricks.spark.util.SparkClientContext$.executeRDD(SparkClientContext.scala:121)
	at org.apache.spark.scheduler.DAGScheduler.submitJob(DAGScheduler.scala:828)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:883)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2245)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2267)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2286)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2311)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1.apply(RDD.scala:951)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1.apply(RDD.scala:949)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:379)
	at org.apache.spark.rdd.RDD.foreachPartition(RDD.scala:949)
	at org.apache.spark.sql.Dataset$$anonfun$foreachPartition$1.apply$mcV$sp(Dataset.scala:2748)
	at org.apache.spark.sql.Dataset$$anonfun$foreachPartition$1.apply(Dataset.scala:2748)
	at org.apache.spark.sql.Dataset$$anonfun$foreachPartition$1.apply(Dataset.scala:2748)
	at org.apache.spark.sql.Dataset$$anonfun$withNewRDDExecutionId$1.apply(Dataset.scala:3409)
	at org.apache.spark.sql.execution.SQLExecution$$anonfun$withCustomExecutionEnv$1.apply(SQLExecution.scala:111)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:240)
	at org.apache.spark.sql.execution.SQLExecution$.withCustomExecutionEnv(SQLExecution.scala:97)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:170)
	at org.apache.spark.sql.Dataset.withNewRDDExecutionId(Dataset.scala:3405)
	at org.apache.spark.sql.Dataset.foreachPartition(Dataset.scala:2747)
	at com.microsoft.azure.sqldb.spark.connect.DataFrameFunctions.bulkCopyToSqlDB(DataFrameFunctions.scala:72)
	at DataLogSqlLoader.bulkCopyLoad(DataLogSqlLoader.scala:34)
	at DataLogSqlLoader.writeTenantDataLogs(DataLogSqlLoader.scala:20)
	at Main$.processSource(Main.scala:133)
	at Main$$anonfun$processSystem$1.apply(Main.scala:81)
	at Main$$anonfun$processSystem$1.apply(Main.scala:79)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
	at Main$.processSystem(Main.scala:79)
	at Main$$anonfun$processTenant$1.apply(Main.scala:72)
	at Main$$anonfun$processTenant$1.apply(Main.scala:70)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
	at Main$.processTenant(Main.scala:70)
	at Main$$anonfun$main$1.apply(Main.scala:63)
	at Main$$anonfun$main$1.apply(Main.scala:61)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
	at Main$.main(Main.scala:61)
	at Main.main(Main.scala)
Disconnected from the target VM, address: '127.0.0.1:58335', transport: 'socket'

Process finished with exit code 1

```

The same code seems to work fine when executing it from a Databricks scala notebook. 
Is this an issue with databricks-connector or this library?

**Comment by arvindshmicrosoft** [comment]
Unfortunately, this connector was never tested with DB-connect and the scenario you describe above is definitely not in scope of this connector. As you can also see, this project is not actively maintained, and as such I would not expect any progress on this issue. I am therefore closing the same. Thank you for your understanding.
