### ISSUE TITLE
Spark 3 support

### ISSUE THREAD

**Issue by tkasu** [Azure/azure-sqldb-spark#80]
As Apache Spark 3.0.0 is now [released](
https://spark.apache.org/news/spark-3-0-0-released.html), what is the timetable to support Spark 3 and Scala 2.12?

**Comment by lotsahelp** [comment]
I'm getting the following exception when running on databricks 7.0.
`	at com.microsoft.azure.sqldb.spark.config.SqlDBConfigBuilder.<init>(SqlDBConfigBuilder.scala:31)
	at com.microsoft.azure.sqldb.spark.config.Config$.apply(Config.scala:254)
	at com.microsoft.azure.sqldb.spark.config.Config$.apply(Config.scala:235)
	at line0419139fc8114231985e78f2bf75c46d25.$read$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-802367102285758:15)
	at line0419139fc8114231985e78f2bf75c46d25.$read$$iw$$iw$$iw$$iw$$iw.<init>(command-802367102285758:67)
	at line0419139fc8114231985e78f2bf75c46d25.$read$$iw$$iw$$iw$$iw.<init>(command-802367102285758:69)
	at line0419139fc8114231985e78f2bf75c46d25.$read$$iw$$iw$$iw.<init>(command-802367102285758:71)
	at line0419139fc8114231985e78f2bf75c46d25.$read$$iw$$iw.<init>(command-802367102285758:73)
	at line0419139fc8114231985e78f2bf75c46d25.$read$$iw.<init>(command-802367102285758:75)
	at line0419139fc8114231985e78f2bf75c46d25.$read.<init>(command-802367102285758:77)
	at line0419139fc8114231985e78f2bf75c46d25.$read$.<init>(command-802367102285758:81)
	at line0419139fc8114231985e78f2bf75c46d25.$read$.<clinit>(command-802367102285758)
	at line0419139fc8114231985e78f2bf75c46d25.$eval$.$print$lzycompute(<notebook>:7)
	at line0419139fc8114231985e78f2bf75c46d25.$eval$.$print(<notebook>:6)
	at line0419139fc8114231985e78f2bf75c46d25.$eval.$print(<notebook>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:745)
	at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:1021)`

**Comment by arvindshmicrosoft** [comment]
Thank you for your questions and ideas. There are no plans to support Spark 3.0.0 with this connector. Consider evaluating the 
[Apache Spark Connector for SQL Server and Azure SQL](https://github.com/microsoft/sql-spark-connector) which is a newer connector. They are already tracking [the request](https://github.com/microsoft/sql-spark-connector/issues/15) for Spark 3.0.0 support in the new connector.

I am closing this issue as there are no plans to address this request in this connector.
