### ISSUE TITLE
Exception while using bulk save

### ISSUE THREAD

**Issue by rkbansal83** [Azure/azure-sqldb-spark#9]
java.lang.NoSuchMethodError: com.microsoft.sqlserver.jdbc.SQLServerBulkCopyOptions.setAllowEncryptedValueModifications(Z)V +details
java.lang.NoSuchMethodError: com.microsoft.sqlserver.jdbc.SQLServerBulkCopyOptions.setAllowEncryptedValueModifications(Z)V
	at com.microsoft.azure.sqldb.spark.bulk.BulkCopyUtils$.getBulkCopyOptions(BulkCopyUtils.scala:109)
	at com.microsoft.azure.sqldb.spark.connect.DataFrameFunctions.com$microsoft$azure$sqldb$spark$connect$DataFrameFunctions$$bulkCopy(DataFrameFunctions.scala:99)
	at 

I am getting above exception while trying to bulk save data frame as described in the documentation.
I double checked SQL Server Driver jar is in claspath of SparkDriver and executors. I am using uber jar attached in this repo

**Comment by rkbansal83** [comment]
Its resolved , classpath on spark-cluster was loading previous version of sql server driver . Changing class loading order did the trick.
